- filename: balakirew_islamei
  slices:
    - [0, 1000, 0]
    - [5000, 22000, 0]
    - [31000, 42000, -1]
- filename: alb_esp3
  slices:
    - [0, 13000, -30]
- filename: alb_esp4
  slices:
    - [0, 14000, -65]
- filename: alb_esp6
  slices:
    - [7000, 12800, -44]
- filename: alb_se3
  slices:
    - [1000, 20000, 0]
- filename: alb_se4
  slices:
    - [0, 18000, -1]
- filename: alb_se5
  slices:
    - [0, 25000,   0]
- filename: alb_se6
  slices:
    - [0, 20000, 0]
- filename: alb_se7
  slices:
    - [0, 12000,   -1]
- filename: alb_se8
  slices:
    - [0, 21000,  -1]
- filename: beethoven_opus10_1
  slices:
    - [0, 33000, -4]
- filename: brahms_opus1_1
  slices:
    - [0, 20000, -75]
- filename: burg_spinnerlied
  slices:
    - [0, 8000, 105]
- filename: chpn_op7_1
  slices:
    - [0, 11000, -1]
- filename: clementi_opus36_1_1
  slices:
    - [0, 5000, -3]
- filename: deb_prel
  slices:
    - [3000, 9000, -4]
    - [13000, 20000, -2]
- filename: god_chpn_op10_e01
  slices:
    - [0, 5000, -2]
- filename: grieg_walzer
  slices:
    - [0, 5800, -41]
- filename: haydn_7_1
  slices:
    - [0, 4000, -2]
- filename: liz_donjuan
  slices:
    - [3000, 15000, -1]
    - [20000, 25000, 0]
    - [29000, 55000, -1]
    - [60000, 80000, 0]
- filename: mos_op36_6
  slices:
    - [1000, 11000, -1]
- filename: muss_1
  slices:
    - [0, 14000, -4]
- filename: mz_311_1
  slices:
    - [0, 22000, -3]
- filename: rac_op3_2
  slices:
    - [0, 11000, -1]
- filename: ravel_miroirs_1
  slices:
    - [0, 22000, -70]
- filename: schubert_D850_1
  slices:
    - [0, 42000, -1]
- filename: schum_abegg
  slices:
    - [4000, 31000, -1]
- filename: ty_januar
  slices:
    - [100, 20000, -104]
